name: Deployment

on:
  pull_request:
    branches: [ "main" ]



jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install jq
      # jq is used to parse JSON when downloading the build artifact
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Step 3: Set Up Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

      # Step 4: Download build artifact from the latest release
      - name: Download Build Artifact from Release
        run: |
          curl -L -o android_builds.tar.gz \
          "$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest \
          | jq -r '.assets[] | select(.name == "android_builds.tar.gz").browser_download_url')"


      # Step 5: Extract the downloaded artifact
      - name: Extract Artifact
        run: |
          mkdir deploy_output
          tar -xzf android_builds.tar.gz -C deploy_output

      # Step 6: Debug artifact contents
      - name: Debug List Downloaded Artifacts
        run: |
          echo "Extracted assets:"
          ls -R deploy_output

      - name: Verify APK File
        run: ls -R deploy_output


      - name: Test APK Path 1
        run: |
          echo "Checking APK file at: deploy_output/app/outputs/apk/release/app-release.apk"
          ls deploy_output/app/outputs/apk/release/app-release.apk || echo "File not found!"

      - name: Test APK Path 2
        run: |
          echo "Checking APK file at: deploy_output/app/outputs/flutter-apk/app-release.apk"
          ls deploy_output/app/outputs/flutter-apk/app-release.apk || echo "File not found!"


      - name: Debug Firebase Secrets
        run: |
          echo "FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}"
          echo "FIREBASE_TESTER_GROUPS: ${{ secrets.FIREBASE_TESTER_GROUPS }}"
          echo "Checking Service Account Key..."
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" | head -c 50


      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > $HOME/firebase-key.json

      - name: Deploy to Firebase App Distribution
        run: firebase appdistribution:distribute deploy_output/app/outputs/flutter-apk/app-release.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --groups ${{ secrets.FIREBASE_TESTER_GROUPS }}
          --release-notes "Bug fixes and improvements"
          --debug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json

      # Optional: Debug Firebase CLI output
      - name: Debug Firebase Output
        run: echo "Firebase Distribution Completed!"